# Generated by Django 4.2 on 2023-04-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('servername', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('due_date', models.DateTimeField(null=True)),
                ('reminder', models.DateTimeField(null=True)),
                ('assignees', models.ManyToManyField(blank=True, related_name='task', to='bot8.users')),
            ],
        ),
    ]
