# Generated by Django 4.2 on 2023-04-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot8', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='guild',
            field=models.IntegerField(null=True),
        ),
    ]
